package org.xftm.common.dao.base.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xftm.common.dao.base.bean.JobExecutionLog;
import org.xftm.common.dao.base.bean.JobExecutionLogExample;

public interface JobExecutionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    long countByExample(JobExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int deleteByExample(JobExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int insert(JobExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int insertSelective(JobExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    List<JobExecutionLog> selectByExample(JobExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    JobExecutionLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") JobExecutionLog record, @Param("example") JobExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByExample(@Param("record") JobExecutionLog record, @Param("example") JobExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByPrimaryKeySelective(JobExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_EXECUTION_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByPrimaryKey(JobExecutionLog record);
}