package org.xftm.common.dao.base.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xftm.common.dao.base.bean.JobStatusTraceLog;
import org.xftm.common.dao.base.bean.JobStatusTraceLogExample;

public interface JobStatusTraceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    long countByExample(JobStatusTraceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int deleteByExample(JobStatusTraceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int insert(JobStatusTraceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int insertSelective(JobStatusTraceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    List<JobStatusTraceLog> selectByExample(JobStatusTraceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    JobStatusTraceLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") JobStatusTraceLog record, @Param("example") JobStatusTraceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByExample(@Param("record") JobStatusTraceLog record, @Param("example") JobStatusTraceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByPrimaryKeySelective(JobStatusTraceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_STATUS_TRACE_LOG
     *
     * @mbg.generated Tue Apr 07 11:46:40 CST 2020
     */
    int updateByPrimaryKey(JobStatusTraceLog record);
}