server:
  address:
  port: 8070
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: xftm-provider

# Dubbo Application  nacos
## The default value of dubbo.application.name is ${spring.application.name}
## dubbo.application.name=${spring.application.name}
nacos:
  service-address: 10.10.80.21
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}